-- ~/.config/hypr/conf/plugin_settings.lua
-- No plugins are loaded.
--
-- hyprbars (window title bars) is intentionally not loaded. To bring it back,
-- build it from https://github.com/hyprwm/hyprland-plugins (commit matching the
-- Hyprland build date) and load it here with hl.plugin.load(<path to .so>),
-- then configure it with hl.config({ plugin = { hyprbars = { ... } } }).
--
-- hyprexpo was dropped upstream (May 2026) and no longer exists.
