-- Generated by wallust. Hyprland Lua color module. Do not edit manually.
-- Consumed via: local colors = require("conf.colors-hyprland")

return {
	wallpaper = "{{wallpaper}}",

	-- ARGB integer form (single-color fields, e.g. shadow color)
	background = 0xff{{background | strip}},
	foreground = 0xff{{foreground | strip}},
	color0 = 0xff{{color0 | strip}},
	color1 = 0xff{{color1 | strip}},
	color2 = 0xff{{color2 | strip}},
	color3 = 0xff{{color3 | strip}},
	color4 = 0xff{{color4 | strip}},
	color5 = 0xff{{color5 | strip}},
	color6 = 0xff{{color6 | strip}},
	color7 = 0xff{{color7 | strip}},
	color8 = 0xff{{color8 | strip}},
	color9 = 0xff{{color9 | strip}},
	color10 = 0xff{{color10 | strip}},
	color11 = 0xff{{color11 | strip}},
	color12 = 0xff{{color12 | strip}},
	color13 = 0xff{{color13 | strip}},
	color14 = 0xff{{color14 | strip}},
	color15 = 0xff{{color15 | strip}},

	-- String form (gradients / plugin fields expecting Hyprland color text)
	background_str = "rgb({{background | strip}})",
	foreground_str = "rgb({{foreground | strip}})",
	color5_str = "rgb({{color5 | strip}})",
	color9_str = "rgb({{color9 | strip}})",
	active_border = "rgb({{color5 | strip}}) rgb({{color11 | strip}}) 45deg",
}
